import Head from "next/head"
import { AppProps } from "next/app"
import React from "react"
import localFont from "next/font/local"
import "../style/globals.css"
import { I18nextProvider } from "react-i18next"
import i18n from "@/components/helper/lang"
import { QueryClient, QueryClientProvider } from "@tanstack/react-query"

const client = new QueryClient({
  defaultOptions: {
    queries: {
      refetchOnWindowFocus: false, // default: true
    },
  },
})

const myFont: any = localFont({ src: "../../public/font/Rabar_022.ttf" })
function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title> cars</title>
        <meta name="description" content="Generated by create cars app" />
      </Head>
      {/* <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      > */}
        <QueryClientProvider client={client}>
            <I18nextProvider i18n={i18n}>
                <main
                  dir="ltr"
                  className={myFont.className}
                >
                  <Component {...pageProps} />
                </main>
            </I18nextProvider>
        </QueryClientProvider>
      {/* </ThemeProvider> */}
    </>
  )
}

export default MyApp
